USE WAREHOUSE COMETL_SFDC_XSMALL_WH;

USE DATABASE COMETL_SFDC_PRD_DB;

USE SCHEMA COMETL_SFDC_CONTROL;  
  
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE AUDIT_DTLS TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE BATCH_RUN_DTLS TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_VLDTN_AUDIT_DTLS TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE DATA_VLDTN_RULE TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ERROR_DTLS TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE FILE_PROCESS_CONFIG TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE FMR_STTM_CONTROL TO ROLE COMETL_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PARAMETER_TABLE TO ROLE COMETL_RW_ROLE;
  
  
USE SCHEMA COMETL_SFDC_STAGING;  
GRANT SELECT ON TABLE ICUE_FMR_VEEVA_ALIGNMENT_TEMP TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_VEEVA_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_OM_ALIGNMENT_TEMP TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_OM_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_OM_VEEVA_ALIGNMENT_360 TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_OM_VEEVA_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_ALIGNMENT_FINAL TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_SYNC;  
GRANT SELECT ON TABLE ICUE_FMR_VS_ALIGNMENT TO ROLE COMETL_RW_ROLE;

USE SCHEMA COMETL_SFDC_LANDING;  
GRANT SELECT ON TABLE ICUE_FMR_PRODUCT_BRAND_INTRM TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE ICUE_FMR_PRODUCT_BRAND TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_CONTROL;  
GRANT USAGE ON PROCEDURE SP_AUDIT_LOG(VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,FLOAT,FLOAT,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT USAGE ON PROCEDURE SP_BATCH_DTLS(VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT USAGE ON PROCEDURE SP_DATA_VALDTN_INS(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT USAGE ON PROCEDURE SP_DATA_VALDTN_UPD(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT USAGE ON PROCEDURE SP_FMR_DATA_LOAD(VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT USAGE ON PROCEDURE SP_FMR_US_ALIGNMENT_LOAD(VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;


USE SCHEMA COMETL_SFDC_STAGING;
GRANT USAGE ON SEQUENCE ICUE_FMR_US_ALIGNMENT_SEQ TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON SEQUENCE ICUE_FMR_US_ALIGNMENT_SEQ TO ROLE COMETL_RW_ROLE;
  
  
  
  
USE SCHEMA COMETL_SFDC_CONTROL;  
  
GRANT ALL ON TABLE AUDIT_DTLS TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE BATCH_RUN_DTLS TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE DATA_VLDTN_AUDIT_DTLS TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE DATA_VLDTN_RULE TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ERROR_DTLS TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE FILE_PROCESS_CONFIG TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE FMR_STTM_CONTROL TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE PARAMETER_TABLE TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_STAGING;  
GRANT ALL ON TABLE ICUE_FMR_VEEVA_ALIGNMENT_TEMP TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_VEEVA_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_OM_ALIGNMENT_TEMP TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_OM_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_OM_VEEVA_ALIGNMENT_360 TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_OM_VEEVA_ALIGNMENT TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_ALIGNMENT_FINAL TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_SYNC;  
GRANT ALL ON TABLE ICUE_FMR_VS_ALIGNMENT TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_LANDING;  
GRANT ALL ON TABLE ICUE_FMR_PRODUCT_BRAND_INTRM TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE ICUE_FMR_PRODUCT_BRAND TO ROLE COMETL_RW_ROLE;
  
USE SCHEMA COMETL_SFDC_CONTROL;  
GRANT ALL,USAGE ON PROCEDURE SP_AUDIT_LOG(VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,FLOAT,FLOAT,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE SP_BATCH_DTLS(VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE SP_DATA_VALDTN_INS(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE SP_DATA_VALDTN_UPD(VARCHAR,VARCHAR,VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE SP_FMR_DATA_LOAD(VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE SP_FMR_US_ALIGNMENT_LOAD(VARCHAR,VARCHAR) TO ROLE COMETL_RW_ROLE;
GRANT ALL,USAGE ON PROCEDURE ICUE_FMR_US_ALIGNMENT_SEQ TO ROLE COMETL_RW_ROLE;


USE SCHEMA COMETL_SFDC_REPL;
GRANT SELECT ON TABLE COMETL_SFDC_REPL.ICUE_FMR_OM_CUST_PROD_SALES_AREA_CLONE1 TO ROLE COMETL_RW_ROLE;
GRANT SELECT ON TABLE COMETL_SFDC_REPL.ICUE_FMR_SF_OBJECTTERRITORY2ASSOCIATION_CLONE1 TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE COMETL_SFDC_REPL.ICUE_FMR_OM_CUST_PROD_SALES_AREA_CLONE1 TO ROLE COMETL_RW_ROLE;
GRANT ALL ON TABLE COMETL_SFDC_REPL.ICUE_FMR_SF_OBJECTTERRITORY2ASSOCIATION_CLONE1 TO ROLE COMETL_RW_ROLE;
