USE WAREHOUSE COMETL_SFDC_XSMALL_WH;

USE DATABASE COMETL_SFDC_PRD_DB;

USE SCHEMA COMETL_SFDC_STAGING;

CREATE OR REPLACE SEQUENCE COMETL_SFDC_STAGING.ICUE_FMR_US_ALIGNMENT_SEQ START = 1 , INCREMENT = 1;