CREATE OR REPLACE WAREHOUSE COMETL_SFDC_XSMALL_WH WITH WAREHOUSE_SIZE='X-Small';

USE WAREHOUSE COMETL_SFDC_XSMALL_WH;

CREATE or replace DATABASE COMETL_SFDC_PRD_DB
DATA_RETENTION_TIME_IN_DAYS = 30
MAX_DATA_EXTENSION_TIME_IN_DAYS = 30;

USE DATABASE COMETL_SFDC_PRD_DB;

CREATE SCHEMA COMETL_SFDC_LANDING;
CREATE SCHEMA COMETL_SFDC_STAGING;
CREATE SCHEMA COMETL_SFDC_CONTROL ;
CREATE SCHEMA COMETL_SFDC_SYNC ;
CREATE SCHEMA COMETL_SFDC_REPL;
CREATE SCHEMA COMETL_SFDC_SCRATCH ;
CREATE SCHEMA COMETL_SFDC_PUBLISH ;

CREATE ROLE COMETL_RW_ROLE;

GRANT USAGE ON WAREHOUSE COMETL_SFDC_XSMALL_WH TO ROLE COMETL_RW_ROLE;


GRANT USAGE ON DATABASE COMETL_SFDC_PRD_DB TO ROLE COMETL_RW_ROLE;



GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_PRD_DB.COMETL_SFDC_PUBLISH TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_LANDING TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_STAGING TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_PRD_DB.COMETL_SFDC_CONTROL TO ROLE COMETL_RW_ROLE ;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_SYNC TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_PRD_DB.COMETL_SFDC_REPL TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_SCRATCH TO ROLE COMETL_RW_ROLE;
GRANT USAGE,ALL ON SCHEMA COMETL_SFDC_PUBLISH TO ROLE COMETL_RW_ROLE;

GRANT ROLE COMETL_RW_ROLE TO ROLE DEVOPS;